@tabela_simbolos = Array.new

@tabela_simbolos.push(Token.new("inicio","inicio",nil))
@tabela_simbolos.push(Token.new("varinicio","varinicio",nil))
@tabela_simbolos.push(Token.new("varfim","varfim",nil))
@tabela_simbolos.push(Token.new("escreva","escreva",nil))
@tabela_simbolos.push(Token.new("leia","leia",nil))
@tabela_simbolos.push(Token.new("se","se",nil))
@tabela_simbolos.push(Token.new("entao","entao",nil))
@tabela_simbolos.push(Token.new("fimse","fimse",nil))
@tabela_simbolos.push(Token.new("facaAte","facaAte",nil))
@tabela_simbolos.push(Token.new("fimfaca","fimfaca",nil))
@tabela_simbolos.push(Token.new("inteiro","inteiro","inteiro"))
@tabela_simbolos.push(Token.new("lit","lit","literal"))
@tabela_simbolos.push(Token.new("real","real","real"))
@tabela_simbolos.push(Token.new("fim","fim",nil))