@gram = [
"",
"P'→ P",
"P→ inicio V A",
"V→ varincio LV",
"LV→ D LV",
"LV→ varfim ;",
"D→ L TIPO ;",
"L→ id , L",
"L→ id",
"TIPO→ int",
"TIPO→ real",
"TIPO→ lit",
"A→ ES A",
"ES→ leia id ;",
"ES→ escreva ARG ;",
"ARG→ literal",
"ARG→ num",
"ARG→ id",
"A→ CMD A",
"CMD→ id rcb LD ;",
"LD→ OPRD opm OPRD",
"LD→ OPRD",
"OPRD→ id",
"OPRD→ num",
"A→ COND A",
"COND→ CAB CP",
"CAB→ se ( EXP_R ) então",
"EXP_R→ OPRD opr OPRD",
"CP→ ES CP",
"CP→ CMD CP",
"CP→ COND CP",
"CP→ fimse",
"A→ R A",
"R→ facaAte ( EXP_R ) CP_R",
"CP_R→ ES CP_R",
"CP_R→ CMD CP_R",
"CP_R→ COND CP_R",
"CP_R→ fimFaca",
"A→ fim"
]